/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

class Persona(private var nombre: String = "" , private var apellido: String = "", private var edad: Int = 0){
    fun inicializar(nombre: String, apellido: String, edad: Int) {
            this.nombre=nombre
            this.apellido=apellido
            this.edad=edad
    }
    override fun toString():String{
        return "(nombre = ${nombre}, apellido = ${apellido}, edad = ${edad})"
        /* */ 
        
    }
}

fun main() {
    var app: Persona
    app = Persona()
    app.inicializar("Daniel", "Quinteros", 50) 
    println("Mi persona es ${app.toString()}")
}

/*# Consigna: Clase Persona en Kotlin

## Objetivo

Crear una clase `Persona` en Kotlin que modele los datos básicos de una persona.

## Requisitos

1. La clase debe llamarse `Persona`.
2. Debe tener los siguientes **atributos privados**:
   - `nombre` (String)
   - `apellido` (String)
   - `edad` (Int)
3. Implementar un **constructor** que reciba los tres parámetros e inicialice los atributos.
4. Sobrescribir el método `toString()` para que devuelva una representación en cadena de la persona con el formato:
   ```
   Persona(nombre=Juan, apellido=Pérez, edad=30)
   ```

## Ejemplo de uso esperado

```kotlin
fun main() {
    val p = Persona("Juan", "Pérez", 30)
    println(p)  // Persona(nombre=Juan, apellido=Pérez, edad=30)
}
```

## Entrega

Subir el archivo `Persona.kt` con la implementación completa.
 */